### ISSUE TITLE
Question regarding the type of plot used in the paper

### ISSUE THREAD

**Issue by emorevival** [Notebook-Factory/RRIFT_notebooks#3]
Hi, there is this plot in the paper: 

![image](https://user-images.githubusercontent.com/32765662/104778214-4bd96900-577d-11eb-9506-6f445901707d.png)

Is it acceptable to do it like this?

![image](https://user-images.githubusercontent.com/32765662/104778345-7e836180-577d-11eb-80db-e8e7af8a2f4b.png)

I'm not sure if this is the way to do it, or if there is a better way.

**Comment by agahkarakuzu** [comment]
@emorevival if the red circles represent data points and the underlying black line is the best line fit (probably is because R<sup>2</sup> is given) belonging to those points, then the way you represent here is missing some steps.

You can run a simple linear fit to these data points and visualize the fit line. Then, the black line would not simply connect the centers of the blue circles as it currently does.

**Comment by zelenkastiot** [comment]
@emorevival regarding the similarity to the original plot and esthetics, it's okay but you can still make it better. 

- Firstly, add an annotation for the R2 (annotations link: https://plotly.com/python/text-and-annotations/, if you want to be like a latex (to have a square of R, try '$R^{2}=0.9958$') 
- Make it with red, not blue circles 
- Make the background white 
- Maybe limit the axes:
  -  [0, 0.4] for the y-axis 
  - [0, 6] for the x-axis 
 -  Add tickvals (see [Figure 4-B](https://notebook-factory.github.io/NeuralDecoding_book/03/subsection/02-04-05/sos_notebook4.html) ) for reference: 
![image](https://user-images.githubusercontent.com/37374247/104780400-09199000-5781-11eb-8f11-b734d4b6a46a.png)
- Try making single axes instead of mirrored ones

**Comment by ddimoski** [comment]
Thanks for the help, this is the updated figure with the linear fit and the styling changes:
![screenshot](https://user-images.githubusercontent.com/20287217/105377646-537c9000-5c0b-11eb-9059-cf5a886df49a.png)
If you think the plot needs further adjustments let us know.

**Comment by agahkarakuzu** [comment]
@ddimoski this looks good to me, now the plot is an accurate representation of the original version.

**Comment by zelenkastiot** [comment]
Great job @ddimoski @emorevival! Looks much better 🚀
